# Generated by Django 5.2.7 on 2025-11-19 01:24

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id_envio', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_envio', models.CharField(max_length=60)),
                ('estado', models.CharField(max_length=40)),
                ('fecha_salida', models.DateTimeField()),
                ('fecha_llegada', models.DateTimeField(blank=True, null=True)),
                ('peso_total', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Existencia',
            fields=[
                ('id_existencia', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('estado', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id_marca', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120)),
                ('direccion', models.TextField()),
                ('correo', models.CharField(max_length=120)),
                ('telefono', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=50, unique=True)),
                ('clave', models.CharField(max_length=128)),
                ('nombre', models.CharField(max_length=150)),
                ('apellido', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('GERENTE', 'Gerente'), ('ADMINISTRADOR', 'Administrador'), ('VENDEDOR', 'Vendedor'), ('ALMACENISTA', 'Almacenista'), ('TRANSPORTISTA', 'Transportista')], default='VENDEDOR', max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.TextField()),
                ('correo', models.CharField(max_length=120)),
                ('telefono', models.CharField(max_length=20)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id_compra', models.AutoField(primary_key=True, serialize=False)),
                ('metodo_pago', models.CharField(max_length=50)),
                ('fecha_pedido', models.DateField()),
                ('estado_de_envio', models.CharField(max_length=40)),
                ('precio_final', models.DecimalField(decimal_places=2, max_digits=12)),
                ('peso_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cancelacion', models.BooleanField(default=False)),
                ('estado_de_pago', models.CharField(max_length=30)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('id_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id_orden', models.AutoField(primary_key=True, serialize=False)),
                ('metodo_pago', models.CharField(max_length=50)),
                ('fecha_orden', models.DateField()),
                ('estado_de_envio', models.CharField(max_length=40)),
                ('precio_final', models.DecimalField(decimal_places=2, max_digits=12)),
                ('peso_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cancelacion', models.BooleanField(default=False)),
                ('estado_de_pago', models.CharField(max_length=30)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.cliente')),
                ('id_envio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.envio')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fecha_creacion', models.DateField()),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('peso_unidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.categoria')),
                ('id_marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.marca')),
            ],
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id_lote', models.AutoField(primary_key=True, serialize=False)),
                ('numero_lote', models.CharField(max_length=60)),
                ('fecha_pedido', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('cantidad', models.IntegerField()),
                ('estado', models.CharField(max_length=30)),
                ('id_inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.existencia')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.producto')),
            ],
        ),
        migrations.AddField(
            model_name='existencia',
            name='id_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.producto'),
        ),
        migrations.CreateModel(
            name='DetalleOrden',
            fields=[
                ('id_detalleo', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('peso_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('peso_subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('devolucion', models.BooleanField(default=False)),
                ('cantidad_devolvida', models.IntegerField(default=0)),
                ('nota', models.TextField(blank=True, null=True)),
                ('id_orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.orden')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.producto')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('id_detalleg', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('peso_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('peso_subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('devolucion', models.BooleanField(default=False)),
                ('cantidad_devolvida', models.IntegerField(default=0)),
                ('nota', models.TextField(blank=True, null=True)),
                ('id_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.compra')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.producto')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroAccion',
            fields=[
                ('id_registro', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_y_hora', models.DateTimeField(auto_now_add=True)),
                ('modulo', models.CharField(max_length=60)),
                ('accion', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('id_referencia', models.IntegerField(blank=True, null=True)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id_unidad', models.AutoField(primary_key=True, serialize=False)),
                ('capacidad_carga', models.DecimalField(decimal_places=2, max_digits=12)),
                ('codigo_unidad', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=20)),
                ('estado', models.CharField(max_length=40)),
                ('placa', models.CharField(max_length=15)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='envio',
            name='id_unidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.unidad'),
        ),
    ]
