# Generated by Django 5.2.7 on 2025-11-22 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id_unidad', models.AutoField(primary_key=True, serialize=False)),
                ('capacidad_carga', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transportista', models.CharField(max_length=150)),
                ('codigo_unidad', models.CharField(max_length=50, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('estado', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=50, unique=True)),
                ('clave', models.CharField(max_length=128)),
                ('nombre', models.CharField(max_length=150)),
                ('tipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id_envio', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_envio', models.CharField(max_length=50, unique=True)),
                ('estado', models.CharField(max_length=50)),
                ('fecha_salida', models.DateField()),
                ('fecha_llegada', models.DateField(blank=True, null=True)),
                ('peso_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('id_unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.unidad')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroAccion',
            fields=[
                ('id_registro', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('modulo', models.CharField(max_length=100)),
                ('accion', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('id_referencia', models.IntegerField(blank=True, null=True)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.usuario')),
            ],
        ),
    ]
