# Generated by Django 5.1.5 on 2025-11-24 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='estado_de_envio',
            field=models.CharField(default='PENDIENTE POR APROBACIÓN', max_length=40),
        ),
        migrations.AlterField(
            model_name='orden',
            name='estado_de_pago',
            field=models.CharField(default='PENDIENTE POR PAGO', max_length=30),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='registroaccion',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='registroaccion',
            name='id_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='registroaccion',
            name='modulo',
            field=models.CharField(max_length=100),
        ),
    ]
