# Generated by Django 5.2.7 on 2026-01-10 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_cliente_activo_alter_cliente_correo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="codigo_recuperacion",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name="usuario",
            name="fecha_recuperacion",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
