# Generated by Django 5.2.7 on 2026-01-19 00:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_usuario_codigo_recuperacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidad',
            name='id_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
