# Generated by Django 5.2.7 on 2026-01-19 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_unidad_id_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoVenta',
            fields=[
                ('id_pagoventa', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('metodo_pago', models.CharField(max_length=50)),
                ('moneda', models.CharField(choices=[('USD', 'Dólar'), ('VES', 'Bolívares')], max_length=3)),
                ('monto_local', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tasa_cambio', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('monto_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('referencia', models.CharField(blank=True, max_length=120)),
                ('id_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_venta', to='base.orden')),
            ],
            options={
                'ordering': ['-fecha_pago'],
            },
        ),
    ]
