# Generated by Django 5.2.7 on 2026-01-19 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_pagoventa'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='rif_cedula',
            field=models.CharField(blank=True, max_length=20, verbose_name='RIF / Cédula'),
        ),
    ]
