# Generated by Django 5.2.7 on 2025-11-22 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('correo', models.CharField(blank=True, max_length=120, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id_compra', models.AutoField(primary_key=True, serialize=False)),
                ('metodo_pago', models.CharField(max_length=50)),
                ('fecha_pedido', models.DateField()),
                ('precio_final', models.DecimalField(decimal_places=2, max_digits=12)),
                ('peso_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cancelacion', models.BooleanField(default=False)),
                ('estado_de_envio', models.CharField(choices=[('PENDIENTE_APROBACION', 'Pendiente de Aprobación'), ('APROBADA', 'Aprobada, Pendiente de Recepción'), ('RECIBIDA_PARCIAL', 'Recibida Parcialmente'), ('RECIBIDA_COMPLETA', 'Recibida Completamente'), ('CANCELADA', 'Cancelada')], default='PENDIENTE_APROBACION', max_length=40)),
                ('estado_de_pago', models.CharField(default='PENDIENTE', max_length=30)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.usuario')),
                ('id_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='compras.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('id_detallec', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('peso_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('peso_subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('devolucion', models.BooleanField(default=False)),
                ('cantidad_devolvida', models.IntegerField(default=0)),
                ('nota', models.TextField(blank=True, null=True)),
                ('id_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.compra')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.producto')),
            ],
        ),
    ]
