# Generated by Django 5.2.7 on 2025-11-22 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='peso_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='compra',
            name='precio_final',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
