# Generated by Django 5.2.7 on 2025-12-03 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoCompra',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('metodo_pago', models.CharField(choices=[('TRANSFERENCIA_BS', 'Transferencia (Bs)'), ('PAGO_MOVIL', 'Pago Móvil (Bs)'), ('TRANSFERENCIA_USD', 'Transferencia en Dólares'), ('EFECTIVO_USD', 'Efectivo Divisas'), ('EFECTIVO', 'Efectivo')], max_length=50)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_pago', models.DateField(auto_now_add=True)),
                ('nota', models.TextField(blank=True, null=True)),
                ('id_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='compras.compra')),
            ],
        ),
    ]
