# Generated by Django 5.2.7 on 2025-11-26 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_alter_compra_peso_total_alter_compra_precio_final'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='metodo_pago',
            field=models.CharField(choices=[('TRANSFERENCIA_BS', 'Transferencia (Bs)'), ('PAGO_MOVIL', 'Pago Móvil (Bs)'), ('TRANSFERENCIA_USD', 'Transferencia en Dólares'), ('EFECTIVO_USD', 'Efectivo Divisas')], default='TRANSFERENCIA_BS', max_length=50),
        ),
    ]
