# Generated by Django 5.2.7 on 2025-12-03 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_pagocompra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagocompra',
            name='nota',
        ),
        migrations.AddField(
            model_name='pagocompra',
            name='moneda',
            field=models.CharField(choices=[('USD', 'USD'), ('VES', 'VES')], default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='pagocompra',
            name='monto_local',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='pagocompra',
            name='tasa_cambio',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pagocompra',
            name='metodo_pago',
            field=models.CharField(choices=[('TRANSFERENCIA_BS', 'Transferencia (Bs)'), ('PAGO_MOVIL', 'Pago Móvil (Bs)'), ('EFECTIVO_BS', 'Efectivo (Bs)'), ('TRANSFERENCIA_USD', 'Transferencia ($)'), ('EFECTIVO_USD', 'Efectivo ($)'), ('ZELLE', 'Zelle ($)')], max_length=50),
        ),
    ]
