# Generated by Django 5.2.7 on 2025-11-26 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_alter_compra_metodo_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='estado_de_envio',
            field=models.CharField(blank=True, choices=[('PENDIENTE_APROBACION', 'Pendiente de Aprobación'), ('APROBADA', 'Aprobada, Pendiente de Recepción'), ('RECIBIDA_PARCIAL', 'Recibida Parcialmente'), ('RECIBIDA_COMPLETA', 'Recibida Completamente'), ('CANCELADA', 'Cancelada')], default='PENDIENTE_APROBACION', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='compra',
            name='estado_de_pago',
            field=models.CharField(blank=True, default='PENDIENTE', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='compra',
            name='peso_total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True),
        ),
    ]
