# Generated by Django 5.2.7 on 2026-01-20 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compras", "0003_remove_pagocompra_nota_pagocompra_moneda_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="proveedor",
            name="rif",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
