# Generated by Django 5.2.7 on 2026-01-20 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("compras", "0004_proveedor_rif"),
    ]

    operations = [
        migrations.RenameField(
            model_name="proveedor",
            old_name="rif",
            new_name="rif_cedula",
        ),
    ]
