# Generated by Django 5.2.7 on 2025-11-26 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_alter_compra_estado_de_envio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallecompra',
            name='peso_subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='detallecompra',
            name='peso_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
