# Generated by Django 5.2.7 on 2026-01-21 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0005_rename_rif_proveedor_rif_cedula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='rif_cedula',
        ),
    ]
