# Generated by Django 5.2.7 on 2026-01-21 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compras", "0006_remove_proveedor_rif_cedula"),
    ]

    operations = [
        migrations.AddField(
            model_name="proveedor",
            name="rif_cedula",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
